name: Android CI

on:
  push:
  release:
    types: [published, prereleased]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "8"

      - name: Build with Gradle
        run: chmod +x ./gradlew && ./gradlew build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: app/**/*.apk

      - name: Upload release assets
        if: ${{ github.event_name == 'release' }}
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "app/**/*.apk"
